# Generated by Django 3.1.6 on 2021-03-30 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210329_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avtocourse',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='avtocourse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='avtocourse',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
