# Generated by Django 3.1.6 on 2021-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
